name: ios
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  mongo_dart: ^0.10.3
  meta: ^1.15.0
  cupertino_icons: ^1.0.8
  get: ^4.6.1
  intl_phone_number_input: ^0.7.4
  numeric_keyboard: ^1.1.0
  pin_code_fields: ^8.0.1
  pin_code_view: ^0.3.0+2
  svg_flutter: ^0.0.1
  currency_picker: ^2.0.21
  url_launcher: ^6.2.6
  font_awesome_flutter: ^9.2.0
  shake: ^2.2.0
  share: ^2.0.4 
  ussd_service: ^0.1.1
  flag: ^7.0.0
  shared_preferences: ^2.2.3
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.0.0
  firebase_storage: ^12.0.0
  fluttertoast: ^8.0.0
  firebase_app_check: ^0.3.0
  email_validator: ^2.1.17
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  introduction_screen: ^3.1.14
  path: ^1.9.0
  contacts_service: ^0.6.3
  permission_handler: ^11.3.1
  sign_in_with_apple: ^6.1.1
  flutter_native_contact_picker: ^0.0.6
  flutter_signin_button: ^2.0.0
  device_info_plus: ^10.1.0
  googleapis: ^13.0.0
  path_provider: ^2.1.3
  inapp_flutter_kyc: ^1.1.5
  provider: ^6.1.2
  googleapis_auth: ^1.4.1
  kyc_workflow: ^1.0.13
  animated_widgets: ^1.1.0
  pretty_animated_buttons: ^0.0.1
  lottie: ^3.1.2
  flutter_translate: ^4.1.0
  translator: ^1.0.0
  device_apps: ^2.2.0
  telephony: ^0.2.0
  sms_autofill: ^2.4.0

dependency_overrides:
  http: ^0.13.6
  video_player: ^2.9.1
  whatsapp_unilink: ^2.1.0
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/icon/
    - assets/image/
    - assets/
