name: Build and Release iOS Ipa

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: Build iOS Ipa
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Install Dependencies
        run: flutter pub get -v

      - name: Ensure CocoaPods is up-to-date
        run: pod repo update
        working-directory: ios

      - name: Clean old Pods and Derived Data
        run: |
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Install CocoaPods dependencies
        run: pod install --verbose
        working-directory: ios

      - name: Build iOS Release
        run: flutter build ios --release --no-codesign -v

      - name: Prepare Payload Directory
        run: mkdir -p build/ios/iphoneos/Payload

      - name: Move App to Payload
        run: mv build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/
        if: success()

      - name: Zip the output IPA
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload IPA to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.PAT_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "Congrats"
